### ISSUE TITLE
Error during MS Preprocessing

### ISSUE THREAD

**Issue by AntoniolEm** [mobiusklein/glycresoft#14]
Good morning,

I'm using GlycReSoft to process my glycopeptide MS data, but when I add the sample to the workspace (as MZML file) the preprocess gives me this error after few seconds: ''ERROR-UserIdentity(id=''0'', info= UserMetaDataBundle) @None:error- etc...

How can I fix this issue ?

Have a nice day

Antonio

**Comment by mobiusklein** [comment]
I will need the rest of the text describing the error, or the complete log file from the `<project directory>/task_dir` to answer your question. Could you please share that information?

**Comment by AntoniolEm** [comment]
Hi, this is the full text of the error:

task_process:task_process :177  - ERROR - UserIdentity(id='0', info=UserMetadataBundle({}))@None:error - 'Traceback (most recent call last):\n  File "urllib\\request.py", line 1354, in do_open\n  File "http\\client.py", line 1256, in request\n  File "http\\client.py", line 1302, in _send_request\n  File "http\\client.py", line 1251, in endheaders\n  File "http\\client.py", line 1011, in _send_output\n  File "http\\client.py", line 951, in send\n  File "http\\client.py", line 1425, in connect\n  File "ssl.py", line 500, in wrap_socket\n  File "ssl.py", line 1040, in _create\n  File "ssl.py", line 1309, in do_handshake\nConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "psims\\controlled_vocabulary\\controlled_vocabulary.py", line 377, in _open_url\n  File "urllib\\request.py", line 222, in urlopen\n  File "urllib\\request.py", line 525, in open\n  File "urllib\\request.py", line 542, in _open\n  File "urllib\\request.py", line 502, in _call_chain\n  File "urllib\\request.py", line 1397, in https_open\n  File "urllib\\request.py", line 1357, in do_open\nurllib.error.URLError: <urlopen error [WinError 10054] An existing connection was forcibly closed by the remote host>\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "glycresoft_app\\task\\preprocess_mzml.py", line 141, in preprocess\n  File "glycan_profiling\\task.py", line 324, in start\n  File "glycan_profiling\\profiler.py", line 231, in run\n  File "glycan_profiling\\trace\\sink.py", line 25, in configure_cache\n  File "glycan_profiling\\scan_cache.py", line 120, in configure_storage\n  File "glycan_profiling\\scan_cache.py", line 194, in __init__\n  File "glycan_profiling\\scan_cache.py", line 97, in __init__\n  File "ms_deisotope\\output\\mzml.py", line 311, in __init__\n  File "psims\\mzml\\writer.py", line 269, in controlled_vocabularies\n  File "psims\\xml.py", line 1034, in controlled_vocabularies\n  File "psims\\document.py", line 582, in write\n  File "contextlib.py", line 113, in __enter__\n  File "psims\\document.py", line 607, in begin\n  File "psims\\mzml\\components.py", line 1137, in write_content\n  File "psims\\xml.py", line 670, in version\n  File "psims\\xml.py", line 678, in vocabulary\n  File "psims\\xml.py", line 704, in load\n  File "psims\\controlled_vocabulary\\controlled_vocabulary.py", line 457, in resolve\n  File "psims\\controlled_vocabulary\\controlled_vocabulary.py", line 392, in _open_url\n  File "psims\\controlled_vocabulary\\vendor\\__init__.py", line 13, in _use_vendored_psims_obo\n  File "importlib\\resources.py", line 91, in open_binary\n  File "PyInstaller\\loader\\pyimod03_importers.py", line 542, in open_resource\n  File "pathlib.py", line 1222, in open\n  File "pathlib.py", line 1078, in _opener\nFileNotFoundError: [Errno 2] No such file or directory: \'C:\\\\Program Files\\\\GlycReSoft\\\\resources\\\\bin\\\\glycresoft-cli\\\\psims\\\\controlled_vocabulary\\\\vendor\\\\psi-ms.obo.gz\'\n'

I didn't succeed in finding the log file, hope the text only is sufficient.

**Comment by mobiusklein** [comment]
Thank you. That tells me exactly where the problem is. I should be able to release a fixed version in an hour or so.

**Comment by AntoniolEm** [comment]
Perfect ! Thank you very much, I will wait for your news !

**Comment by mobiusklein** [comment]
I've created a new release that should fix the problem. You can download it [here](https://github.com/BostonUniversityCBMS/glycresoft_desktop/releases/download/v0.4.8/GlycReSoft_0.4.8.exe).

Please let me know whether it fixes your problem or not.

Thank you.

**Comment by AntoniolEm** [comment]
Hi, I am trying to use the new version but unfortunately the software gives me another error:

10:10:34 - root:task_process.py:78   - INFO - Task Running on PID 13296
10:10:34 - glycresoft_app.task.preprocess_mzml:preprocess_mzml.py:33   - INFO - Begin Scan Interpolation
10:10:34 - task_process:task_process.py:143  - ERROR - UserIdentity(id='0', info=UserMetadataBundle({}))@None:error - 'Traceback (most recent call last):
  File "glycresoft_app\\task\\task_process.py", line 81, in configure_log_wrapper
  File "glycresoft_app\\task\\preprocess_mzml.py", line 37, in preprocess
  File "ms_deisotope\\data_source\\scan\\loader.py", line 602, in _locate_ms1_scan
AttributeError: \'NoneType\' object has no attribute \'ms_level\'

Any suggestion the overcome this issue ?

**Comment by AntoniolEm** [comment]
Update, I tried to browse the .raw file instead of the .mzml and the software is running without giving any error for the moment. I will update you.

**Comment by AntoniolEm** [comment]
Update. After I uploaded the .raw file, in analyze sample, and after the process ended the software gave me a file in the samples list (ms/ms sample), but when I try to open the file the following test appears ''something went wrong''. 

Nevertheless, I tried also to run a ''search glycopeptide sequence'' experiment, using the sample file created, however it gives me the following error:

10:42:52 - root:task_process.py:78   - INFO - Task Running on PID 18844
10:42:53 - glycresoft:task.py:364  - INFO - Begin MzML GlycopeptideLCMSMS Analyzer
{'analysis_name': 'gB_noLeader.FASTA at gB_Trypsin_1_20220204144101 (1)',
 'database_connection': 'C:\\Users\\ARD_developer\\Desktop\\Prova\\hypothesis_dir\\gB_noLeader.FASTA_glycopeptde_5.database',
 'extra_msn_evaluation_kwargs': {},
 'file_manager': TempFileManager('C:\\Users\\ARD_DE~1\\AppData\\Local\\Temp\\glycresoft_tmp_zlo6jbu7'),
 'grouping_error_tolerance': 1.4999999999999999e-05,
 'hypothesis_id': 1,
 'mass_error_tolerance': 9.999999999999999e-06,
 'mass_shifts': [MassShift(Unmodified, Composition({}))],
 'maximum_mass': inf,
 'minimum_mass': 1000.0,
 'minimum_oxonium_ratio': 0.05,
 'model_retention_time': True,
 'msn_mass_error_tolerance': 1.9999999999999998e-05,
 'n_processes': 5,
 'output_path': 'C:\\Users\\ARD_developer\\Desktop\\Prova\\results_dir\\gB_noLeader.FASTA_at_gB_Trypsin_1_20220204144101__1_1.analysis.db',
 'peak_shape_scoring_model': ChromatogramScorer('line_score': <glycan_profiling.scoring.shape_fitter.ChromatogramShapeModel object at 0x000001FA74262280>, 'isotopic_fit': <glycan_profiling.scoring.isotopic_fit.IsotopicPatternConsistencyModel object at 0x000001FA742622E0>, 'spacing_fit': <glycan_profiling.scoring.spacing_fitter.ChromatogramSpacingModel object at 0x000001FA74262340>, 'charge_count': <glycan_profiling.scoring.base.DummyFeature object at 0x000001FA742623A0>),
 'permute_decoy_glycans': False,
 'probing_range_for_missing_precursors': 3,
 'psm_fdr_threshold': 0.05,
 'rare_signatures': False,
 'sample_path': 'C:\\Users\\ARD_developer\\Desktop\\Prova\\sample_dir\\gB_Trypsin_1_20220204144101-11.mzML',
 'sample_run_id': -1,
 'save_unidentified': False,
 'scan_transformer': <function GlycopeptideLCMSMSAnalyzer.__init__.<locals>.scan_transformer at 0x000001FA792D15E0>,
 'spectrum_batch_size': 250,
 'start_time': datetime.datetime(2022, 5, 23, 10, 42, 53, 260601),
 'status': 'started',
 'tandem_scoring_model': <class 'glycan_profiling.tandem.glycopeptide.scoring.coverage_weighted_binomial.CoverageWeightedBinomialScorer'>,
 'trust_precursor_fits': True,
 'use_peptide_mass_filter': False}
10:42:56 - glycresoft:profiler.py:939  - INFO - Loading MS/MS
10:43:04 - glycresoft:glycopeptide_matcher.py:174  - INFO - Writing Matches To TempFileManager('C:\\Users\\ARD_DE~1\\AppData\\Local\\Temp\\glycresoft_tmp_zlo6jbu7')
10:43:04 - glycresoft:glycopeptide_matcher.py:178  - INFO - ... Begin Batch
10:43:04 - glycresoft:glycopeptide_matcher.py:178  - INFO - ... controllerType=0 controllerNumber=1 scan=9566: 15824.611116 (+16)
10:43:04 - glycresoft:glycopeptide_matcher.py:178  - INFO - ... 250/7864 (3.179%)
10:43:05 - glycresoft:glycopeptide_matcher.py:180  - INFO - ... 218 Unconfirmed Precursor Spectra
10:43:05 - glycresoft:glycopeptide_matcher.py:181  - INFO - ... Spectra Extracted
10:43:05 - glycresoft:spectrum_evaluation.py:199  - INFO - ... Begin Collecting Hits
10:43:05 - glycresoft:spectrum_evaluation.py:201  - INFO - ... Mapping For Unmodified
10:43:05 - task_process:task_process.py:143  - ERROR - UserIdentity(id='0', info=UserMetadataBundle({}))@None:error - 'Traceback (most recent call last):
  File "glycresoft_app\\task\\analyze_glycopeptide_sequence_data.py", line 160, in analyze_glycopeptide_sequences
  File "glycan_profiling\\task.py", line 396, in start
  File "glycan_profiling\\profiler.py", line 945, in run
  File "glycan_profiling\\profiler.py", line 805, in do_search
  File "glycan_profiling\\tandem\\glycopeptide\\glycopeptide_matcher.py", line 184, in search
  File "glycan_profiling\\tandem\\glycopeptide\\matcher.py", line 344, in score_all
  File "glycan_profiling\\tandem\\glycopeptide\\matcher.py", line 291, in score_bunch
ZeroDivisionError: float division by zero
'
10:43:05 - task_process:task_process.py:143  - ERROR - UserIdentity(id='0', info=UserMetadataBundle({}))@None:error - 'An error occurred during analysis.'
10:43:05 - task_process:task_process.py:143  - ERROR - UserIdentity(id='0', info=UserMetadataBundle({}))@None:error - 'Traceback (most recent call last):
  File "glycresoft_app\\task\\analyze_glycopeptide_sequence_data.py", line 160, in analyze_glycopeptide_sequences
  File "glycan_profiling\\task.py", line 396, in start
  File "glycan_profiling\\profiler.py", line 945, in run
  File "glycan_profiling\\profiler.py", line 805, in do_search
  File "glycan_profiling\\tandem\\glycopeptide\\glycopeptide_matcher.py", line 184, in search
  File "glycan_profiling\\tandem\\glycopeptide\\matcher.py", line 344, in score_all
  File "glycan_profiling\\tandem\\glycopeptide\\matcher.py", line 291, in score_bunch
ZeroDivisionError: float division by zero

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "glycresoft_app\\task\\task_process.py", line 81, in configure_log_wrapper
  File "glycresoft_app\\task\\analyze_glycopeptide_sequence_data.py", line 177, in analyze_glycopeptide_sequences
  File "glycresoft_app\\task\\task_process.py", line 173, in abort
Exception: An error occurred during analysis.
'

Sorry for the several posts.

**Comment by mobiusklein** [comment]
It's not a problem to post several issues, it does mean that something is going wrong in the software somewhere.

When you were creating the mzML file, did you subset the original raw file in any way?

I see how the second problem occurred, but I don't understand what went wrong to generate it. Are you willing to share the raw file and the FASTA file you used to generate your database? I can patch the immediate issue but want to understand how it came to be in the first place.

**Comment by AntoniolEm** [comment]
Hi, what do you mean with ''subset the original raw file'' ? After converting the raw file with MSConvert I obtain another file in format mzML, that I browse on GlyReSoft.

About the FASTA file and the raw file, unfortunately I cannot share these files because of data integrity policy. 

Are you able to fix these issues without the files ?

**Comment by mobiusklein** [comment]
I can still fix the immediate errors, but I won't be able to know their root causes. I'll probably have another build ready within 12 hours.

**Comment by AntoniolEm** [comment]
I understand. 

Could the issue emerge from the specific typology of files that I'm using (that are raw converted in mzML) ? I am using XCALIBUR as program, I don't know if knowing this can help you.

Is it normal that I cannot visualize the analyzed samples? When I click on them the sentence ''something went wrong'' appears.

Thank you.

**Comment by mobiusklein** [comment]
Sorry for the delay, I was caught up with other things at work. I've released a new build v0.4.9 which fixes the zero-division issue you reported, and the problem with viewing a processed MS run, which was broken when I moved from Python 2 to Python 3.

The "view sample" feature should now work again, albeit slowly. That view of the data is not particularly featureful though.

**Comment by AntoniolEm** [comment]
No problem, thank you for the help ! Where can I download the new version of the software ?

**Comment by AntoniolEm** [comment]
Update. I downloaded the new version, but now when I browse a file in analyze sample and click on submit nothing happens (the task-list doesn't give anything ongoing).

**Comment by mobiusklein** [comment]
I'm traveling and do not have regular access to a computer and can't work on this until around Monday.

**Comment by AntoniolEm** [comment]
Update.
I succeed in running the glycopeptide sequence search in ''analyze semple'', the issue was the absence of reverse decoy peptides so I built a new glycopeptide database selecting the option ''generate reverse decoys''.

Now I am comparing the results from GlycReSoft with that from PEAKS, I have noticed that the first one loses a lot of glycoforms and for several N-sequons it doesn't give me any glycan, while on PEAKS there are serveral glycoform describe for that site.

Any suggestion ?

**Comment by mobiusklein** [comment]
How did you conclude that the issue was the absence of reverse decoys? When a reverse protein decoy database isn't constructed, the original algorithm would reverse target peptides instead with no additional effort on the user's part.

I'm assuming this is HCD data. Is that correct? High collision energy, low collision energy, or stepped collision energy?

Is this using PEAKS's new glycopeptide ID module or their original database search procedure? I am not familiar with the new module, but PEAKS's original database search process does not look for glycan fragments and does not attempt to control the FDR for them.

Are the spectra for those lost IDs dominated by peptide+Y ions while others are not? The original database search algorithm in GlycReSoft has poor performance when these are present. You can either generate a non full cross-product search space to use the indexed search strategy which can deal with these better, or select the option to permute decoy glycan fragments to get around this issue, if it is the case.

Are you using a full cross-product database with reverse protein decoys, or without a full cross-product using the indexed search strategy (this needs more work to make it clear on the GUI)?

**Comment by AntoniolEm** [comment]
I tried to run the comand ''search glycopeptide sequences'' using both a without-reverse decoys glycopeptide database and a glycopeptide database with reverse decoys, in the first case the system gave me error, while in the second case the software mange to finish the processing and give me the results, so I deduced that the decoys were the issues.

Yes, you are correct, I'm using HCD data, not stepped, with NCE of 26.

I'm using PEAKS with the DB procedure, I have built a glycan PTM database and I am using the glycosylation as variable modifications.

Yes the glycopeptide spectra that I generate usually have only one dominant ion series (like y), how could I generate a non full cross-product search space or permute decoy glycan framents to get around this issue?

I'm using only the FASTA file of my protein, without any database. I have only one protein to analyze.

**Comment by mobiusklein** [comment]
For a single protein, single energy HCD use case without reliable peptide+Y ions, you're best bet is to use permuted glycan decoys. This can be done just by checking this box when setting up the search in the GUI:
![image](https://user-images.githubusercontent.com/1426041/173079421-24797380-dfea-45de-ad29-4a2a321bca32.png)

If you wanted to create a database for the indexed search strategy, you would just uncheck this box during database construction:
![image](https://user-images.githubusercontent.com/1426041/173080636-229ac6fc-2a6e-493e-9315-fefc1412e819.png)
This would give your search results both a peptide and a glycan FDR, but it relies on having both peptide backbone fragments and intact peptide+glycan fragments (peptide+Y or "stub ions"). 

Are your samples enriched for glycopeptides or are you searching a mix of peptides and glycopeptides in PEAKS? This might be skewing your FDR estimate in PEAKS, but it'd be hard to say how much. 

PEAKS can also identify semitryptic peptides spanning glycosylation sites. There's an option to enable generating a semi-tryptic search space:
![image](https://user-images.githubusercontent.com/1426041/173081450-88466661-4a95-4ac6-b237-641288bd6707.png)
It does dramatically increase the space to consider. Alternatively, if you have an mzIdentML file from PEAKS, you can import that to build your search space, and GlycReSoft will use all observed peptide backbones from that search, limiting the combinatorial explosion.

**Comment by AntoniolEm** [comment]
Sorry for the late answer ! I have been very busy with other projects. 

However I tried to change the filters as you suggested, some peptides appear other still dont'. 
I will try to play with the various parameters until something will change.

Thanks
